### ISSUE TITLE
failOnHint doesn't log errors

### ISSUE THREAD

**Issue by michaelbull** [w3tecch/aurelia-template-lint-loader#1]
Hi,

I am using the following configuration for the loader:

```javascript
    aureliaTemplateLinter: {
        // aurelia errors are displayed by default as warnings
        // set emitErrors to true to display them as errors
        emitErrors: true,

        // aurelia does not interrupt the compilation by default
        // if you want any file with aurelia errors to fail
        // set failOnHint to true
        failOnHint: true,

        // aurelia does not type check by default
        // if you want to do type checking set
        // typeChecking to true and provide
        // the right fileGlob
        // reference https://github.com/MeirionHughes/aurelia-template-lint#static-type-checking
        // these settings can also be passed with configuration above
        typeChecking: true,
        fileGlob: 'src'
    }
```

Building produces the following output after terminating.

```
> cross-env NODE_ENV=production webpack --progress --hide-modules

 69% 208/209 build modules
```

The build has clearly failed for templating reasons. I can confirm this by setting `failOnHint: false` at which point I get:

```
> cross-env NODE_ENV=production webpack --progress --hide-modules

Hash: d1d1473b3bf9d6a9c360
Version: webpack 1.13.3
Time: 24624ms

ERROR in ./src/test.html
[4, 7]: suspected unclosed element detected
[9, 5]: mismatched close tag
[10, 3]: mismatched close tag
[11, 1]: mismatched close tag
```

So I can see the errors by setting `failOnHint` to false, but now I lose the ability to prematurely fail the build on template linting errors - as it now doesn't report until after the distribution has been built.

Please can you fix it so that the errors aren't lost when running with `failOnHint: true`?

Thanks.

**Comment by dweber019** [comment]
@MikeBull94 Will have a look into it soon.

**Comment by dweber019** [comment]
@MikeBull94 this has been fixed with release https://github.com/w3tecch/aurelia-template-lint-loader/releases/tag/1.0.1

**Comment by michaelbull** [comment]
Thanks very much.

**Comment by michaelbull** [comment]
This is still not fixed. The build correctly fails upon a linting error, but when `failOnHint` is set to `true`, the output you get in the console is meaningless and does not detail the actual errors:

```
[at-loader] Using typescript@2.1.4 from typescript and "tsconfig.json" from tsconfig.json.

build modules(node:8291) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Compilation failed due to aurelia template error errors.
```

vs `failOnHint: false`

```
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.298 sec.                                                                                                                        Hash: 97eb9249be6a6c39d1de
Version: webpack 1.14.0
Time: 8574ms

ERROR in ./src/app.html
[5, 5]: self-closing element
```

**Comment by dweber019** [comment]
@MikeBull94 Sorry forgot to publish on npm registry. Should now work.
